#ifndef WEBTILES_GLOBAL_H
#define WEBTILES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBTILES_LIBRARY)
#  define WEBTILESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBTILESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBTILES_GLOBAL_H
